### PR TITLE
Viz

### PR DESCRIPTION
**Pull request by paradite**
added ability to toggle between the table mode (original mode) and bar chart mode.
i modified my codes to ensure consistency of styling.

### CODE REVIEW

**Comment by paradite** [comment]
@yangshun can i merge plz

**Comment by yangshun** [comment]
This PR is not really aligned with the direction of this app. It's always good (for both parties) for a contributor to ask if a maintainer was interested in a feature before building it to prevent wasted work or duplicated efforts, especially considering this is a huge feature and drastically changes the appearance of the page. I think you probably would have learned that by now.

I'll merge it anyway since you have put in the effort and it's a low risk PR, but please bear the above in mind in future.

**Comment by paradite** [comment]
Haha, I didn't really mean it. It's just we were talking about this today in the office and I remembered that I had this PR opened so I commented for fun. This was my first PR on GitHub so it's quite crappy. 😂

**Comment by yangshun** [comment]
-reverted-

**Pull request merged**
